In [1]:
import numpy as np

In [2]:
a=np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[a%2!=0]=999

In [6]:
a

array([999,   2, 999,   4, 999,   6, 999,   8, 999])

In [12]:
b=np.arange(10000000)

In [15]:
b[(b%3==0) & (b%7==0)]

array([      0,      21,      42, ..., 9999948, 9999969, 9999990])

In [14]:
np.array(['Apple','Mi','Huawei','Oppo'])[[1,3,2,0]]

array(['Mi', 'Oppo', 'Huawei', 'Apple'], dtype='<U6')