In [13]:
import numpy as np

In [14]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [15]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
arr.shape

(2, 2, 2)

In [16]:
arr.ndim

3

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.zeros(10,dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones(10,dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
d=np.ones((2,4),dtype='int32')

In [25]:
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.zeros_like(d)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.ones(5,dtype='int32')/5

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [28]:
len(d)

2