In [1]:
import sklearn.datasets as sd
import sklearn.utils as su
import sklearn.metrics as sm
import sklearn.model_selection as ms

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
import cufflinks as cf
from plotly.offline import iplot, plot
import plotly.express as px
import plotly.graph_objects as go
cf.go_offline()

In [4]:
iris = sd.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data['target'] = iris.target
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [6]:
data.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [7]:
data.groupby('target').agg([np.max, np.min])

sepal length (cm)      sepal width (cm)      petal length (cm)       \
                    amax amin             amax amin              amax amin   
target                                                                       
0                    5.8  4.3              4.4  2.3               1.9  1.0   
1                    7.0  4.9              3.4  2.0               5.1  3.0   
2                    7.9  4.9              3.8  2.2               6.9  4.5   

       petal width (cm)       
                   amax amin  
target                        
0                   0.6  0.1  
1                   1.8  1.0  
2                   2.5  1.4

In [8]:
px.scatter(x='petal length (cm)',
           y='petal width (cm)',
           data_frame=data,
           color='target',
           size='sepal length (cm)',
           hover_data=['sepal width (cm)'])

In [9]:
px.scatter(x='sepal length (cm)',
           y='sepal width (cm)',
           color='target',
           size='petal length (cm)',
           data_frame=data)

In [10]:
# 绘制sigmoid图像
x = np.linspace(-10, 10, 2000)
y = 1 / (1 + np.exp(-x))
go.Figure(data=go.Scatter(x=x, y=y))

In [11]:
X = data.drop('target', axis=1)
y = data['target']
X_train, X_test, y_train, y_test = ms.train_test_split(X,
                                                       y,
                                                       test_size=0.1,
                                                       random_state=7)

import sklearn.linear_model as lm
model = lm.LogisticRegression(solver='liblinear', multi_class='auto')
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [12]:
print(sm.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      0.43      0.60         7
           2       0.43      1.00      0.60         3

    accuracy                           0.73        15
   macro avg       0.81      0.81      0.73        15
weighted avg       0.89      0.73      0.73        15



In [13]:
print(sm.confusion_matrix(y_test, predictions))

[[5 0 0]
 [0 3 4]
 [0 0 3]]


In [14]:
X_test[predictions != y_test]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
84                5.4               3.0                4.5               1.5
66                5.6               3.0                4.5               1.5
77                6.7               3.0                5.0               1.7
85                6.0               3.4                4.5               1.6